### ISSUE TITLE
install

### ISSUE THREAD

**Issue by gtmp7** [noisegate/fbpy#1]
Hi 
This package looks quite impressive. Unfortunately for me, I encounter problem installing it on Linux Mint 17.1 Rebecca : 
sudo python setup.py install
Traceback (most recent call last):
  File "setup.py", line 27, in <module>
    ext_modules = cythonize(extensions)
  File "/usr/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 707, in cythonize
    aliases=aliases)
  File "/usr/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 633, in create_extension_list
    kwds = deps.distutils_info(file, aliases, base).values
  File "/usr/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 543, in distutils_info
    return (self.transitive_merge(filename, self.distutils_info0, DistutilsInfo.merge)
  File "/usr/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 553, in transitive_merge
    node, extract, merge, seen, {}, self.cimported_files)[0]
  File "/usr/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 564, in transitive_merge_helper
    for next in outgoing(node):
  File "/usr/lib/python2.7/dist-packages/Cython/Utils.py", line 29, in wrapper
    res = cache[args] = f(self, _args)
  File "/usr/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 492, in cimported_files
    pxd_file = self.find_pxd(module, filename)
  File "/usr/lib/python2.7/dist-packages/Cython/Utils.py", line 29, in wrapper
    res = cache[args] = f(self, *args)
  File "/usr/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 476, in find_pxd
    pxd = self.context.find_pxd_file(relative, None)
  File "/usr/lib/python2.7/dist-packages/Cython/Compiler/Main.py", line 184, in find_pxd_file
    pxd = self.search_include_directories(qualified_name, ".pxd", pos, sys_path=True)
  File "/usr/lib/python2.7/dist-packages/Cython/Compiler/Main.py", line 225, in search_include_directories
    tuple(self.include_directories), qualified_name, suffix, pos, include, sys_path)
  File "/usr/lib/python2.7/dist-packages/Cython/Utils.py", line 16, in wrapper
    res = cache[args] = f(_args)
  File "/usr/lib/python2.7/dist-packages/Cython/Utils.py", line 101, in search_include_directories
    path = os.path.join(dir, dotted_filename)
  File "/usr/lib/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 10: ordinal not in range(128)

Python is 2.7.6 
Any idea ?
Thanks in advance

**Comment by noisegate** [comment]
Thnx for pointing this out, I'll take a look in the morning

**Comment by noisegate** [comment]
could you try installing in a dir without codepoint>127 in the path, eg áúőé stuff? just to see if this matters

**Comment by gtmp7** [comment]
Well done, you got it indeet there was an accent in the path ! But still, I get an error :
sudo python setup.py install
running install
running build
running build_py
running build_ext
building 'fblib' extension
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c ./fbpy/utils/fblib.c -o build/temp.linux-x86_64-2.7/./fbpy/utils/fblib.o
In file included from /usr/include/python2.7/numpy/ndarraytypes.h:1761:0,
                 from /usr/include/python2.7/numpy/ndarrayobject.h:17,
                 from /usr/include/python2.7/numpy/arrayobject.h:4,
                 from ./fbpy/utils/fblib.c:237:
/usr/include/python2.7/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
In file included from ./fbpy/utils/fblib.c:239:0:
./fbpy/utils/test.h:10:1: warning: useless storage class specifier in empty declaration [enabled by default]
 };
 ^
In file included from ./fbpy/utils/fblib.c:240:0:
./fbpy/utils/audio.h:24:23: fatal error: jack/jack.h: Aucun fichier ou dossier de ce type (=No such file or directory)
 #include <jack/jack.h>
                       ^
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
Seem the c-header file jack.h is missing. Not to be find in the repo. Might be in some other package you've wrote, or you just forgot to include it ?
Thank a lot for your help

**Comment by noisegate** [comment]
Do you need Jack ( Jack Audio Connection Kit)? If not I'll send you a link
for a version without Jack. If yes you should install Jack dev.
Op 20 jun. 2015 22:41 schreef "gtmp7" notifications@github.com:

**Comment by noisegate** [comment]
Op 20 jun. 2015 23:42 schreef "Marcell Marosvolgyi" <
marcell.marosvolgyi@gmail.com>:

> Do you need Jack ( Jack Audio Connection Kit)? If not I'll send you a
> link for a version without Jack. If yes you should install Jack

libjack-dev that is

**Comment by gtmp7** [comment]
Thanks for the hints. I installed libjack (although I am not so much interested in that feature, but no pb). The install went ok, but demo.py fails after at the 3rd screen :
"""                                But we can also gen our own characters...  
 Using the built in svg lib and prefab svg charset:  
Traceback (most recent call last):
File "demo.py", line 261, in <module>
Welcome.helloworld()
File "demo.py", line 97, in helloworld
tekst1 = svg.Text((10,10),"invoking svg module", 1.5, cls.midd)
File "/usr/local/lib/python2.7/dist-packages/fbpy/svg.py", line 93, in **init**
self.printtext()
  File "/usr/local/lib/python2.7/dist-packages/fbpy/svg.py", line 109, in printtext
  self.surf.addpoly(p.x,p.y,p.z)
  File "/usr/local/lib/python2.7/dist-packages/fbpy/fb.py", line 119, in wrapper
  return self(instance, _args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fbpy/fb.py", line 115, in **call**
  return self.function(_args, *_kwargs) 
  File "/usr/local/lib/python2.7/dist-packages/fbpy/fb.py", line 904, in addpoly
   return fblib.fbaddpoly(x1,y1,z1)
  File "fblib.pyx", line 325, in fbpy.utils.fblib.fbaddpoly (./fbpy/utils/fblib.c:5146)
  TypeError: fbaddpoly() takes exactly 4 positional arguments (3 given)"""
The only thing it get displayed in the text swirling down from the first screen of demo.py. That happens only if go system "direct" tty (Ctrl Alt 1)  and not from graphics term emulator like konsole (might be because I can't get dev/pts/1 from konsole, since you say you need precisely that tty in the demo txt ).

I also tried some of your examples from the doc :
In [1]: import fbpy

In [2]: import fbpy.fb as fb

In [3]: main = fb.Surface()
surpress debug info
yres = 1050
In [4]: sub = fb.Surface((100,100),(600,600))

In [11]: sub.blit("./primitives.png")
Out[11]: 0
But nothing is displayed (either konsole or CtrlAlt+1). 

Any ideas ?

Thanks in advance

**Comment by noisegate** [comment]
oops, yep I can reproduce the error. I'll look into that ... 
sorry about the delay, please give me 4 more days or so...

**Comment by rufinus2** [comment]
Hello Marcel,

i would like to install fbpy without jack, as i don't need it. Can you please send me a link to download?

Thanks
