### ISSUE TITLE
Cannot perform relative import

### ISSUE THREAD

**Issue by jkronen** [noisegate/fbpy#7]
Hey, I just installed fbpy on my Raspberry Pi Zero but I can't import it.

```
sudo apt-get install libffi-dev libjack-dev
sudo pip3 install cython
sudo pip3 install numpy
export CFLAGS="-l /usr/local/lib/python3.4/dist-packages/numpy/core/include/"
sudo pip3 install cffi
sudo pip3 install JACK-client
git clone https://github.com/noisegate/fbpy.git
```

Then I changed the install.sh to python3 and added 
`include_dirs=[np.get_include()]`
to the setup.py

Then running the install.sh as sudo made it possible to install fbpy.

But now I can't import it

```
[10:58] pi@recpi ~/fbpy >python3
Python 3.4.2 (default, Oct 19 2014, 13:31:11) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fbpy.fb as fb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/fbpy/fbpy/fb.py", line 22, in <module>
    import fblib
  File "fbpy/utils/fblib.pyx", line 27, in init fbpy.utils.fblib (./fbpy/utils/fblib.c:9813)
    import numpy as np
SystemError: Parent module '' not loaded, cannot perform relative import
```

**Comment by jkronen** [comment]
Eh, I didn't see the python3.x branch...
