### ISSUE TITLE
blib and grab not working

### ISSUE THREAD

**Issue by jkronen** [noisegate/fbpy#8]
Hey, 

I finally installed the python3 version. Everything works except blib and grab. I used the examples in the documentation

```
[11:24] pi@raspberry ~ >python3
Python 3.4.2 (default, Oct 19 2014, 13:31:11) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fbpy.fb as fb
>>> main = fb.Surface()
surpress debug info
yres = 272>>> sub = fb.Surface((0,0), (200,200))
>>> sub.clear()
0
>>> sub.blit("/home/pi/fbpy/test.png")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/fbpy/fb.py", line 1241, in blit
    return fblib.fbblit(filename)
  File "fbpy/utils/fblib.pyx", line 268, in fbpy.utils.fblib.fbblit (./fbpy/utils/fblib.c:4400)
TypeError: expected bytes, str found

```

EDIT: The examples won't work as well

**Comment by noisegate** [comment]
Take a look at it next week, sorry been busy with so many other projects..
